// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0E5LxXz3l6tdSSITpaEiA1sF6jPr4Mg',
    appId: '1:92536473318:web:2bff6cb251cb0157179d27',
    messagingSenderId: '92536473318',
    projectId: 'intranetweb-68536',
    authDomain: 'intranetweb-68536.firebaseapp.com',
    storageBucket: 'intranetweb-68536.appspot.com',
    measurementId: 'G-0934VN0XTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQSHQpIgT4Ouh3vwZHyVkqu-6AltfntEc',
    appId: '1:92536473318:android:b224e4319ee42b8b179d27',
    messagingSenderId: '92536473318',
    projectId: 'intranetweb-68536',
    storageBucket: 'intranetweb-68536.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOGGVh-K5cZkhlpi8s4YJskevop6HMP30',
    appId: '1:92536473318:ios:6562f21c7144c517179d27',
    messagingSenderId: '92536473318',
    projectId: 'intranetweb-68536',
    storageBucket: 'intranetweb-68536.appspot.com',
    iosBundleId: 'com.zeelearn.intranet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOGGVh-K5cZkhlpi8s4YJskevop6HMP30',
    appId: '1:92536473318:ios:e4807a6ab826e745179d27',
    messagingSenderId: '92536473318',
    projectId: 'intranetweb-68536',
    storageBucket: 'intranetweb-68536.appspot.com',
    iosBundleId: 'com.zeelearn.intranet.RunnerTests',
  );
}
