// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDvVRpknNCx8KTmy1TO-BXW6kPmzPEyNc',
    appId: '1:411998223312:web:3ec3c688769d9aa2dd97d5',
    messagingSenderId: '411998223312',
    projectId: 'intranet-9fda2',
    authDomain: 'intranet-9fda2.firebaseapp.com',
    databaseURL: 'https://intranet-9fda2-default-rtdb.firebaseio.com',
    storageBucket: 'intranet-9fda2.appspot.com',
    measurementId: 'G-5DZKG2P4P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGUg3e_G7TzpwXWcX3KOyxCmYyCXiroDE',
    appId: '1:411998223312:android:176ef77cd8fca5e4dd97d5',
    messagingSenderId: '411998223312',
    projectId: 'intranet-9fda2',
    databaseURL: 'https://intranet-9fda2-default-rtdb.firebaseio.com',
    storageBucket: 'intranet-9fda2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpFlcHfIyHFmc1xQGxlP7aTfm5bwzI_Zk',
    appId: '1:411998223312:ios:0dabf3a3a966fb4cdd97d5',
    messagingSenderId: '411998223312',
    projectId: 'intranet-9fda2',
    databaseURL: 'https://intranet-9fda2-default-rtdb.firebaseio.com',
    storageBucket: 'intranet-9fda2.appspot.com',
    iosClientId: '411998223312-0svaok9ad4mid7v6t4f6vj8vi7q30a3g.apps.googleusercontent.com',
    iosBundleId: 'com.zeelearn.intranet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpFlcHfIyHFmc1xQGxlP7aTfm5bwzI_Zk',
    appId: '1:411998223312:ios:0dabf3a3a966fb4cdd97d5',
    messagingSenderId: '411998223312',
    projectId: 'intranet-9fda2',
    databaseURL: 'https://intranet-9fda2-default-rtdb.firebaseio.com',
    storageBucket: 'intranet-9fda2.appspot.com',
    iosClientId: '411998223312-0svaok9ad4mid7v6t4f6vj8vi7q30a3g.apps.googleusercontent.com',
    iosBundleId: 'com.zeelearn.intranet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa4mT4N2D2TlVhVFkghSMAwsWxaolYBTI',
    appId: '1:411998223312:web:5a054b7dc4841ed0dd97d5',
    messagingSenderId: '411998223312',
    projectId: 'intranet-9fda2',
    authDomain: 'intranet-9fda2.firebaseapp.com',
    databaseURL: 'https://intranet-9fda2-default-rtdb.firebaseio.com',
    storageBucket: 'intranet-9fda2.appspot.com',
    measurementId: 'G-35YVLKPYT8',
  );

}